cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('', include('drugstore.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

drugstore/urls.py
from django.urls import path
from . import views

app_name = 'drugstore'

urlpatterns = [
    path('', views.get_product_list, name='product_list'),
    path('search_product/', views.search_product, name='search'),
    path('add-product/', views.create_product, name='add_product'),
    path('update-product/<str:product_slug>/', views.update_product, name='update_product'),
    path('delete/<str:product_slug>/', views.delete_product, name='delete_product'),
    path('product-like/<int:id>/', views.like_product, name="product_like_url"),
    path('product/detail/<str:product_slug>/', views.get_product_detail, name='product_details'),
    path('products/<str:product_slug>/', views.get_product_detail, name='product_details'),
    path('export/', views.write_db),
    path('<str:category_slug>/', views.get_product_list, name='product_list_by_category'),
]

drugstore/models.py
from django.db import models
from django.urls import reverse

from account.models import MyUser


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        
        return reverse('drugstore:product_list_by_category',
                       args=[self.slug, ])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveSmallIntegerField(default=0)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        
        return reverse('drugstore:product_details',
                       args=[self.slug, ])

    def save(self):
        self.slug = self.name.lower().replace(" ", '-')
        return super().save()


class Comment(models.Model):
    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    user = models.ForeignKey('account.MyUser', related_name='comment', on_delete=models.CASCADE, blank=True)
    product = models.ForeignKey(Product, related_name='comment', on_delete=models.CASCADE, blank=True)
    text = models.TextField('Enter comment:', max_length=500)
    create_at = models.DateTimeField(auto_now_add=True)
    moder = models.BooleanField(default=False)

class Like(models.Model):
    user = models.ForeignKey(MyUser, related_name='likes', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='likes', on_delete=models.CASCADE)


    def str(self):
        return f'{self.user}:{self.product.name}'

drugstore/forms.py
from django.forms import ModelForm, ValidationError
from .models import Product, Comment


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'slug')

    def clean(self):
        slug = self.cleaned_data.get('name').lower().replace(" ", '-')
        if Product.objects.filter(slug=slug).exists():
            raise ValidationError('Product with such name already exists!')
        return self.cleaned_data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

drugstore/views.py
from unicodedata import category
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponse
from cart.forms import CartAddProductForm
from cart.helpers import Cart
from .forms import ProductForm
from .helpers import product_list_filter_sort
from .models import Category, Product, Like
from .models import Comment
from .forms import CommentForm

def search_product(request):
    category = None
    categories = Category.objects.all()
    products = None
    search = request.GET.get('search')
    if search:
        products = Product.objects.filter(Q(name__icontains=search) |
                                          Q(description__icontains=search)
                                          )
    context = {
        'products': products,
        'categories': categories,
        'category': category
    }
    return render(
        request,
        'product/product_list.html',
        context
    )


def get_product_list(request, category_slug=None):
    """Функция вытаскивает продукты и если слаг приходит заполненым
    то фильтрует по слагу и в конце возвращаем контексты
    """

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('-created_at')
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    # фильтрацию по прайс и по категориям
    products = product_list_filter_sort(
        request,
        products,
        category_slug
    )

    paginator = Paginator(products, settings.PAGINATOR_NUM)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {
        'products': products,
        'categories': categories,
        'category': category,
    }
    return render(
        request,
        'product/product_list.html',
        context
    )


def get_product_detail(request, product_slug):
    """Детализация продукта
    """
    categories = Category.objects.all()
    product = get_object_or_404(Product, slug=product_slug)
    cart_product_form = CartAddProductForm()
    comment = Comment.objects.filter(product=product)
    likes = product.likes.all().count()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.user = request.user
            comm.product = product
            comm.save()
    else:
        form = CommentForm()

    return render(
        request, 'product/product_detail.html', locals()
    )


def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            # product = Product.objects.create(**form.cleaned_data)
            return redirect(product.get_absolute_url())
    else:
        form = ProductForm()

    return render(request, 'product/create_product.html', {'product_form': form})


def update_product(request, product_slug):
    obj = get_object_or_404(Product, slug=product_slug)
    form = ProductForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        product = form.save()
        # product = Product.objects.create(**form.cleaned_data)
        return redirect(product.get_absolute_url())

    return render(request, 'product/update_product.html', {'product_form': form})



def delete_product(request, product_slug):
    p = Product.objects.get(slug=product_slug)
    Cart(request).remove(p) 
    p.delete() 
    return redirect('/')


def like_product(request, id):
    product = get_object_or_404(Product, id=request.POST.get('product_id'))
    if Like.objects.filter(user=request.user, product=product).exists():
        Like.objects.get(user=request.user, product=product).delete()
    else:
        Like.objects.create(user=request.user, product=product)
    return redirect('drugstore:product_details', product.slug)

def write_db(request):
    import csv
    import os
    open('db.csv', 'w').close()
    products = Product.objects.all()
    with open('db.csv', 'w') as f:
        writer = csv.writer(f, delimiter=',')
        writer.writerow(('product_id', 'category', 'name', 'price'))
        for product in products:
            writer.writerow((product.id, product.category, product.name, product.price))
    with open('db.csv') as f:
        db = f.read()
    os.remove('db.csv')
    return HttpResponse(db, content_type='application/csv')

drugstore/templates/base.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>DRUGSTORE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
			<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="/" class="logo"><strong>DRUGSTORE</strong></a>
									{%block content2 %} {% endblock %}
									<ul class="icons">
										<li><a href="https://github.com/NurgazyBekmurzaev/drugstore-" class="icon brands fa-github"><span class="label">Github</span></a></li>
										<li><a href="https://t.me/python_itkg" class="icon brands fa-telegram"><span class="label">telegram</span></a></li>
										<li><a href="https://www.instagram.com/makerskg/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
										<li><a href="https://www.youtube.com/channel/UCGd7UBX4wOc3XnYMjXB312A/videos" class="icon brands fa-youtube"><span class="label">Instagram</span></a></li>
										<li><a href="https://makers.kg/"><span class="label">Makers</span></a></li>
									</ul>
								</header>

							<!-- Banner -->
							<div id="content">
							{% block content %}
								Empty Content
							{% endblock content %}
							</div>
						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">
							<ul style="list-style:none;display:flex;flex-direction:column;justify-content: space-around;height: 35vh;">
								<li>
									<a href="/" class="navbar-brand">DRUGSTORE</a>
								</li>
								{% if request.user.is_staff %}
								<li>
									<a href="/add-product"><i class="fa-duotone fa-plus"></i></a>
								</li>
								{% endif %}
								{% if request.user.is_authenticated %}
								{% with total_items=cart|length%}
									{% if cart|length > 0%}
										<li>
											Your cart:
											<a href="{% url 'cart:cart_detail' %}">
												<i class="fa-solid fa-cart-shopping"></i>
												{{total_items}} item{{total_items|pluralize}},
												${{ cart.get_total_price }}

											</a>
										</li>

									{% else %}
										<li>
											Your cart is empty
										</li>
									{% endif %}
								{% endwith %}
								<li>
									<a href="/account/logout"><i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a>
								</li>
								{% else %}
								<li>
									<a href="/account/sign_up"><i class="fa-solid fa-user-plus"></i> Sign up</a>
								</li>
								<li>
									<a href="/account/login"><i class="fa-solid fa-user-check"></i> Login</a>
								</li>
								{% endif %}



								<form class="d-flex" action="{% url 'drugstore:search' %}" style="display:flex;align-items:center">
									<input class="form-control me-2 mr-2" name="search" type="search" placeholder="Search" aria-label="Search">
									<button type="submit">Search</button>
								</form>
							</ul>


							<!-- Menu -->
								<nav id="menu">
									<ul>
										<li>
											<span class="opener">PRODUCT CATEGORIES</span>
											<ul>
												{% for cat in categories %}
												<li {% if category.slug == cat.slug %}class="selected"{% endif %}>
												  <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
												</li>
										  		{% endfor %}
											</ul>
									</ul>
								</nav>

							<!-- Footer -->
								<footer id="footer">
									<p class="copyright"> Address: Bishkek city, Isanova str. №13б, Contacts: +996 501 619 690, makers@gmail.com Design: <a href="https://makers.kg/">Makers</a>.</p>
								</footer>

						</div>
					</div>

			</div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/browser.min.js' %}"></script>
			<script src="{% static 'js/breakpoints.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>

</html>