cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('', include('drugstore.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

drugstore/urls.py
from django.urls import path
from . import views

app_name = 'drugstore'

urlpatterns = [
    path('', views.get_product_list, name='product_list'),
    path('search_product/', views.search_product, name='search'),
    path('add-product/', views.create_product, name='add_product'),
    path('update-product/<str:product_slug>/', views.update_product, name='update_product'),
    path('delete/<str:product_slug>/', views.delete_product, name='delete_product'),
    path('product-like/<int:id>/', views.like_product, name="product_like_url"),
    path('product/detail/<str:product_slug>/', views.get_product_detail, name='product_details'),
    path('products/<str:product_slug>/', views.get_product_detail, name='product_details'),
    path('export/', views.write_db),
    path('<str:category_slug>/', views.get_product_list, name='product_list_by_category'),
]

drugstore/models.py
from django.db import models
from django.urls import reverse

from account.models import MyUser


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        
        return reverse('drugstore:product_list_by_category',
                       args=[self.slug, ])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveSmallIntegerField(default=0)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        
        return reverse('drugstore:product_details',
                       args=[self.slug, ])

    def save(self):
        self.slug = self.name.lower().replace(" ", '-')
        return super().save()


class Comment(models.Model):
    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    user = models.ForeignKey('account.MyUser', related_name='comment', on_delete=models.CASCADE, blank=True)
    product = models.ForeignKey(Product, related_name='comment', on_delete=models.CASCADE, blank=True)
    text = models.TextField('Enter comment:', max_length=500)
    create_at = models.DateTimeField(auto_now_add=True)
    moder = models.BooleanField(default=False)

class Like(models.Model):
    user = models.ForeignKey(MyUser, related_name='likes', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='likes', on_delete=models.CASCADE)


    def str(self):
        return f'{self.user}:{self.product.name}'

drugstore/forms.py
from django.forms import ModelForm, ValidationError
from .models import Product, Comment


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'slug')

    def clean(self):
        slug = self.cleaned_data.get('name').lower().replace(" ", '-')
        if Product.objects.filter(slug=slug).exists():
            raise ValidationError('Product with such name already exists!')
        return self.cleaned_data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

drugstore/views.py
from unicodedata import category
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponse
from cart.forms import CartAddProductForm
from cart.helpers import Cart
from .forms import ProductForm
from .helpers import product_list_filter_sort
from .models import Category, Product, Like
from .models import Comment
from .forms import CommentForm

def search_product(request):
    category = None
    categories = Category.objects.all()
    products = None
    search = request.GET.get('search')
    if search:
        products = Product.objects.filter(Q(name__icontains=search) |
                                          Q(description__icontains=search)
                                          )
    context = {
        'products': products,
        'categories': categories,
        'category': category
    }
    return render(
        request,
        'product/product_list.html',
        context
    )


def get_product_list(request, category_slug=None):
    """Функция вытаскивает продукты и если слаг приходит заполненым
    то фильтрует по слагу и в конце возвращаем контексты
    """

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('-created_at')
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    # фильтрацию по прайс и по категориям
    products = product_list_filter_sort(
        request,
        products,
        category_slug
    )

    paginator = Paginator(products, settings.PAGINATOR_NUM)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {
        'products': products,
        'categories': categories,
        'category': category,
    }
    return render(
        request,
        'product/product_list.html',
        context
    )


def get_product_detail(request, product_slug):
    """Детализация продукта
    """
    categories = Category.objects.all()
    product = get_object_or_404(Product, slug=product_slug)
    cart_product_form = CartAddProductForm()
    comment = Comment.objects.filter(product=product)
    likes = product.likes.all().count()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.user = request.user
            comm.product = product
            comm.save()
    else:
        form = CommentForm()

    return render(
        request, 'product/product_detail.html', locals()
    )


def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            # product = Product.objects.create(**form.cleaned_data)
            return redirect(product.get_absolute_url())
    else:
        form = ProductForm()

    return render(request, 'product/create_product.html', {'product_form': form})


def update_product(request, product_slug):
    obj = get_object_or_404(Product, slug=product_slug)
    form = ProductForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        product = form.save()
        # product = Product.objects.create(**form.cleaned_data)
        return redirect(product.get_absolute_url())

    return render(request, 'product/update_product.html', {'product_form': form})



def delete_product(request, product_slug):
    p = Product.objects.get(slug=product_slug)
    Cart(request).remove(p) 
    p.delete() 
    return redirect('/')


def like_product(request, id):
    product = get_object_or_404(Product, id=request.POST.get('product_id'))
    if Like.objects.filter(user=request.user, product=product).exists():
        Like.objects.get(user=request.user, product=product).delete()
    else:
        Like.objects.create(user=request.user, product=product)
    return redirect('drugstore:product_details', product.slug)

def write_db(request):
    import csv
    import os
    open('db.csv', 'w').close()
    products = Product.objects.all()
    with open('db.csv', 'w') as f:
        writer = csv.writer(f, delimiter=',')
        writer.writerow(('product_id', 'category', 'name', 'price'))
        for product in products:
            writer.writerow((product.id, product.category, product.name, product.price))
    with open('db.csv') as f:
        db = f.read()
    os.remove('db.csv')
    return HttpResponse(db, content_type='application/csv')

drugstore/templates/product/create_product.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ product_form.as_p }}
        <button type="submit" class="btn btn-secondary">Create</button>
    </form>
{% endblock %}

drugstore/templates/product/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="400" height="400">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>
    {{ product.description|linebreaks }}
    <form action="{% url 'drugstore:product_like_url' product.id %}" method="POST" >
      {% if request.user.is_authenticated %}
      {% csrf_token %}
        <button type="submit" name="product_id" value="{{ product.id }}">Like</button>
      {% endif %}
        <p>Likes: {{likes}}</p>
    </form>
    {% if user.is_authenticated %}
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    {% endif %}
    {% if user.is_authenticated %}
	  <div>
	  <h3>Comments {{ comment.count }}</h3>
              {% for comm in comment %}
              {{ comm.user }} -- {{ comm.create_at}} <br>
              {{ comm.text }} <br><br>
              {% endfor %}
              <p>
              <form action="" method="post">
                  {% csrf_token %}
                  {{form}}
                  <input type="submit" value="Send">
              </form>
                </p>
	  </div>
    {% endif %}
    {% if request.user.is_staff %}
      <div class="d-flex justify-content-between total font-weight-bold mt-4">
		  <a href="{% url 'drugstore:update_product' product.slug %}"><button type="button" class="btn btn-success">Update</button></a>
        <a href="{% url 'drugstore:delete_product' product.slug %}"><button type="button" class="btn btn-danger">Delete</button></a>
      </div>
    {% endif %}
  </div>

{% endblock %}

drugstore/templates/product/product_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{%block content2 %} 
<a href="{% url 'drugstore:product_list' %}?-price=sort">Expensive</a>
<a href="{% url 'drugstore:product_list' %}?price=sort">Low</a>
{% endblock %}
{% block content %}
	<section id="banner">
		<div class="content">
				{% for product in products %}
				  <div class="item">
					<a href="{{ product.get_absolute_url }}">
					  <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="200" height="200">
					</a><br>
					<a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br><br>
					${{ product.price }}
				  </div>
				{% endfor %}
		</div>
	</section>

{% if products %}
<div class="pagination">
    <span class="step-links">
        {% if products.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ products.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ products.number }} of {{ products.paginator.num_pages }}.
        </span>

        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}">next</a>
            <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

drugstore/templates/product/update_product.html
  
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
      {% csrf_token %}
	{{ product_form.as_p }}

<button type="submit" class="btn btn-secondary">Update</button>
</form>
{% endblock %}