cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('', include('drugstore.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

drugstore/urls.py
from django.urls import path
from . import views

app_name = 'drugstore'

urlpatterns = [
    path('', views.get_product_list, name='product_list'),
    path('search_product/', views.search_product, name='search'),
    path('add-product/', views.create_product, name='add_product'),
    path('update-product/<str:product_slug>/', views.update_product, name='update_product'),
    path('delete/<str:product_slug>/', views.delete_product, name='delete_product'),
    path('product-like/<int:id>/', views.like_product, name="product_like_url"),
    path('product/detail/<str:product_slug>/', views.get_product_detail, name='product_details'),
    path('products/<str:product_slug>/', views.get_product_detail, name='product_details'),
    path('export/', views.write_db),
    path('<str:category_slug>/', views.get_product_list, name='product_list_by_category'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, 21)
]



class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES
    )
    update = forms.BooleanField(
        required=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
)
from django.views.decorators.http import require_http_methods

from cart.forms import CartAddProductForm
from cart.helpers import Cart
from drugstore.models import Product


@require_http_methods(['POST'])
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add_or_update(
            product=product,
            quantity=cleaned_data['quantity'],
            update_quantity=cleaned_data['update']
        )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    return render(request,
                  'cart_detail.html',{}
                  )

cart/templates/cart_detail.html
{% extends "base.html" %}
<!--{% load static %}-->
<!--{% block title %}-->
<!--    Your shopping cart-->
<!--{% endblock %}-->
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img style="width: 200px;" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'drugstore:product_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'order:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock %}